# Generated by Django 4.1 on 2022-08-07 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=800)),
                ('icon', models.CharField(max_length=200)),
                ('is_rest', models.BooleanField(default=False)),
                ('is_work', models.BooleanField(default=False)),
                ('is_learning', models.BooleanField(default=False)),
                ('is_self_care', models.BooleanField(default=False)),
                ('is_exercise', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=800)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitiesApp.activitycategory')),
            ],
        ),
    ]
