# Generated by Django 4.1 on 2022-09-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitiesApp', '0002_activity_user_activitycategory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activitiesApp.activitycategory'),
        ),
    ]
