# Generated by Django 4.1 on 2022-09-27 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitiesApp', '0003_alter_activity_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('time_spent', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activitiesApp.activity')),
            ],
        ),
    ]
