# Generated by Django 4.1 on 2022-10-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitiesApp', '0005_activityfollowup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='current_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='spent_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='spent_time_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityfollowup',
            name='started_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
