# Generated by Django 4.1 on 2022-10-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitiesApp', '0006_activity_current_month_activity_spent_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='current_month',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='spent_time_month',
        ),
    ]
