# Generated by Django 4.1 on 2022-10-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitiesApp', '0007_remove_activity_current_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycategory',
            name='is_driving',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='is_entertainment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='is_feeding',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='is_idle',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='is_loving',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='is_planning',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='is_playing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
