# Generated by Django 4.1 on 2022-10-31 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=800)),
                ('is_accomplished', models.BooleanField(blank=True, default=False, null=True)),
                ('dead_line_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=800)),
                ('is_positive', models.BooleanField(blank=True, default=False, null=True)),
                ('is_negative', models.BooleanField(blank=True, default=False, null=True)),
                ('Goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lifeGoals.goal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalObjetive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=800)),
                ('is_accomplished', models.BooleanField(blank=True, default=False, null=True)),
                ('Goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lifeGoals.goal')),
            ],
        ),
    ]
