# Generated by Django 4.1 on 2022-10-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitsApp', '0004_habitfollowup'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitfollowup',
            name='daily_goal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='habitfollowup',
            name='is_accomplished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='habitfollowup',
            name='is_failed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
