# Generated by Django 4.1 on 2023-01-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitsApp', '0005_habitfollowup_daily_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='timer_goal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='times_goal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
