# Generated by Django 4.1 on 2023-01-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitsApp', '0006_habit_timer_goal_habit_times_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitfollowup',
            name='daily_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
