# Generated by Django 4.1 on 2022-11-01 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activitiesApp', '0008_activitycategory_is_driving_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('is_canceled', models.BooleanField(blank=True, default=False, null=True)),
                ('date_line', models.DateField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(blank=True, default=False, null=True)),
                ('priority', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activitiesApp.activitycategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
