# Generated by Django 4.1 on 2022-08-07 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulmates', '0002_alter_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 7, 21, 22, 42, 108052)),
        ),
    ]
