# Generated by Django 4.1 on 2023-01-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitmeasures',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
